let currentReport={candidates:[],themes:[],tracking:[],summary:{}};
let sectorMarket='all';
let expandedSector='';
const nf=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:1});
const mf=new Intl.NumberFormat('ja-JP',{notation:'compact',maximumFractionDigits:1});
const $=id=>document.getElementById(id);
const val=id=>$(id)?.value||'';
const setText=(id,text)=>{const e=$(id);if(e)e.textContent=text;};
const setHtml=(id,html)=>{const e=$(id);if(e)e.innerHTML=html;};
function fmt(v,s=''){if(v===undefined||v===null||v===''||Number.isNaN(v))return'-';return typeof v==='number'?`${nf.format(v)}${s}`:`${v}${s}`;}
function money(v){return v?`$${mf.format(v)}`:'-';}
function avg(arr){const xs=arr.filter(v=>typeof v==='number'&&!Number.isNaN(v));return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;}
function marketLabel(m){return m==='JP'?'日本株':m==='US'?'米国株':m||'-';}
function setupLabel(t){return{breakout:'ブレイク候補',pullback:'押し目候補',theme_leader:'テーマリーダー',high_volatility:'高ボラ注意',trend_watch:'トレンド監視',watch_only:'監視のみ',avoid:'除外寄り'}[t]||t||'未分類';}
function rankClass(r){return r==='S'?'rank-s':r==='A'?'rank-a':r==='B'?'rank-b':r==='C'?'rank-c':'rank-d';}
function priority(i){if(i.rank==='S')return'最優先';if(i.rank==='A')return'優先監視';if(i.setupType==='high_volatility')return'サイズ注意';if(i.setupType==='avoid')return'見送り寄り';return'監視';}
function links(i){const c=i.code||String(i.symbol||'').replace('.T','');if(i.market==='US')return`<a href="https://finance.yahoo.com/quote/${i.symbol}" target="_blank" rel="noopener noreferrer">Yahoo</a><a href="https://www.tradingview.com/symbols/${i.symbol}/" target="_blank" rel="noopener noreferrer">TradingView</a>`;return`<a href="https://kabutan.jp/stock/?code=${c}" target="_blank" rel="noopener noreferrer">株探</a><a href="https://finance.yahoo.co.jp/quote/${c}.T" target="_blank" rel="noopener noreferrer">Yahoo</a><a href="https://jp.tradingview.com/symbols/TSE-${c}/" target="_blank" rel="noopener noreferrer">TradingView</a>`;}
function passRank(rank,filter){if(filter==='S')return rank==='S';if(filter==='A')return['S','A'].includes(rank);if(filter==='B')return['S','A','B'].includes(rank);return true;}
function filtered(){const q=val('searchInput').trim().toLowerCase();const m=val('marketFilter')||'all';const r=val('rankFilter')||'all';const st=val('setupFilter')||'all';const sort=val('sortSelect')||'score';return[...(currentReport.candidates||[])].filter(i=>{const h=`${i.symbol||''} ${i.code||''} ${i.name||''} ${i.theme||''} ${i.market||''}`.toLowerCase();if(q&&!h.includes(q))return false;if(m!=='all'&&i.market!==m)return false;if(!passRank(i.rank,r))return false;if(st!=='all'&&i.setupType!==st)return false;return true;}).sort((a,b)=>{if(sort==='turnover')return(b.metrics?.avgTradingValue20Usd||0)-(a.metrics?.avgTradingValue20Usd||0);if(sort==='atr')return(a.metrics?.atrPct??999)-(b.metrics?.atrPct??999);if(sort==='ret60')return(b.metrics?.ret60Pct??-999)-(a.metrics?.ret60Pct??-999);return(b.score||0)-(a.score||0);});}
function computedSectorRows(){const groups={};(currentReport.candidates||[]).forEach(i=>{const key=`${i.market||'-'}|${i.theme||'未分類'}`;if(!groups[key])groups[key]=[];groups[key].push(i);});return Object.entries(groups).map(([key,items])=>{const [m,theme]=key.split('|');const leaders=[...items].sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,8);const sCount=items.filter(i=>i.rank==='S').length;const aCount=items.filter(i=>i.rank==='A').length;const breakout=items.filter(i=>i.setupType==='breakout').length;const pullback=items.filter(i=>i.setupType==='pullback').length;const highVol=items.filter(i=>i.setupType==='high_volatility').length;const strength=Math.round(avg(items.map(i=>i.score||0))*10)/10;const ret20=Math.round(avg(items.map(i=>i.metrics?.ret20Pct))*10)/10;const ret60=Math.round(avg(items.map(i=>i.metrics?.ret60Pct))*10)/10;const atr=Math.round(avg(items.map(i=>i.metrics?.atrPct))*10)/10;const turnover=items.reduce((sum,i)=>sum+(i.metrics?.avgTradingValue20Usd||0),0);return{key,market:m,theme,items,leaders,sCount,aCount,breakout,pullback,highVol,strength,ret20,ret60,atr,turnover,strengthChange:0,changeLabel:'初回'};});}
function sectorRows(){let rows=(currentReport.sectorStrength&&currentReport.sectorStrength.length?currentReport.sectorStrength:computedSectorRows()).map(r=>({...r,key:r.key||`${r.market}|${r.theme}`}));if(sectorMarket!=='all')rows=rows.filter(r=>r.market===sectorMarket);const sort=val('sectorSortSelect')||'change';return rows.sort((a,b)=>{if(sort==='change')return(b.strengthChange??0)-(a.strengthChange??0);if(sort==='ret20')return(b.ret20??0)-(a.ret20??0);if(sort==='ret60')return(b.ret60??0)-(a.ret60??0);if(sort==='turnover')return(b.turnover??0)-(a.turnover??0);if(sort==='leaders')return((b.sCount*2+b.aCount)-(a.sCount*2+a.aCount));return(b.strength??0)-(a.strength??0);});}
function changeText(r){const c=r.strengthChange;if(c===undefined||c===null)return'前回比 -';if(c>0)return`前回比 +${fmt(c)}`;if(c<0)return`前回比 ${fmt(c)}`;return r.changeLabel==='new'?'新規':'前回比 0';}
function heatClass(v){if(v>=85)return'heat-5';if(v>=75)return'heat-4';if(v>=65)return'heat-3';if(v>=55)return'heat-2';return'heat-1';}
function setCandidateTheme(theme,market){if($('searchInput'))$('searchInput').value=theme;if($('marketFilter'))$('marketFilter').value=market||'all';location.hash='#candidates';renderCandidates();renderRiskTable();}
function renderSummary(){const s=currentReport.summary||{};const cards=[['対象',s.total??currentReport.candidates?.length??0],['S',s.sRank??0],['A',s.aRank??0],['ブレイク',s.breakoutReady??0],['押し目',s.pullbackReady??0],['高ボラ',s.highVolatility??0],['平均',s.averageScore??'-']];setHtml('summaryCards',cards.map(([l,v])=>`<article class="summary-card"><span>${l}</span><strong>${v}</strong></article>`).join(''));}
function renderMarketSummary(){const s=currentReport.marketSummary||{};setHtml('marketSummary',['JP','US'].map(m=>{const r=s[m]||{};return`<article class="market-card"><span>${marketLabel(m)}</span><strong>${r.selectedRows??0}銘柄</strong><p>入力 ${r.inputRows??0} / S ${r.sRank??0} / A ${r.aRank??0} / 平均 ${r.averageScore??'-'}</p></article>`;}).join(''));}
function renderSectors(){const rows=sectorRows();const stronger=rows.filter(r=>(r.strengthChange??0)>0).slice(0,8);setHtml('strongerThemes',stronger.map(r=>`<button class="heat-tile ${heatClass(r.strength)}" type="button" data-open-sector="${r.key}"><strong>${r.theme}</strong><span>${marketLabel(r.market)} / ${changeText(r)}</span></button>`).join('')||'<p class="empty">前回比データは次回実行から表示されます。</p>');setHtml('sectorHeatmap',rows.slice(0,30).map(r=>`<button class="heat-tile ${heatClass(r.strength)}" type="button" data-open-sector="${r.key}"><strong>${r.theme}</strong><span>${marketLabel(r.market)} / 強さ ${fmt(r.strength)} / ${changeText(r)}</span></button>`).join('')||'<p class="empty">セクターデータがありません。</p>');setHtml('sectorGrid',rows.map(r=>{const open=expandedSector===r.key;const leaders=(r.leaders||[]).slice(0,8);const detail=open?`<div class="sector-detail"><div class="sector-actions"><button type="button" data-filter-theme="${r.theme}" data-filter-market="${r.market}">このテーマの候補へ</button></div><table><thead><tr><th>#</th><th>銘柄</th><th>ランク</th><th>スコア</th><th>型</th><th>20日</th><th>60日</th><th>ATR</th></tr></thead><tbody>${leaders.map((i,idx)=>`<tr><td>${idx+1}</td><td>${i.symbol}<br>${i.name}</td><td>${i.rank||'-'}</td><td>${fmt(i.score)}</td><td>${setupLabel(i.setupType)}</td><td>${fmt(i.metrics?.ret20Pct,'%')}</td><td>${fmt(i.metrics?.ret60Pct,'%')}</td><td>${fmt(i.metrics?.atrPct,'%')}</td></tr>`).join('')}</tbody></table></div>`:'';return`<article class="sector-card ${open?'open':''}"><button class="sector-toggle" type="button" data-open-sector="${r.key}"><div><span>${marketLabel(r.market)} / ${changeText(r)}</span><strong>${r.theme}</strong></div><div class="sector-score"><b>${fmt(r.strength)}</b><small>強さ</small></div></button><div class="sector-meta"><span>20日 ${fmt(r.ret20,'%')}</span><span>60日 ${fmt(r.ret60,'%')}</span><span>ATR ${fmt(r.atr,'%')}</span><span>S ${r.sCount} / A ${r.aCount}</span><span>BO ${r.breakout} / PB ${r.pullback} / HV ${r.highVol}</span><span>${money(r.turnover)}</span></div>${detail}</article>`;}).join('')||'<p class="empty">セクターデータがありません。</p>');setHtml('sectorTable',`<table><thead><tr><th>市場</th><th>セクター</th><th>強さ</th><th>前回比</th><th>20日</th><th>60日</th><th>ATR</th><th>S/A</th><th>型</th><th>売買代金</th><th>リーダー</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${marketLabel(r.market)}</td><td>${r.theme}</td><td>${fmt(r.strength)}</td><td>${changeText(r)}</td><td>${fmt(r.ret20,'%')}</td><td>${fmt(r.ret60,'%')}</td><td>${fmt(r.atr,'%')}</td><td>S ${r.sCount}<br>A ${r.aCount}</td><td>BO ${r.breakout}<br>PB ${r.pullback}<br>HV ${r.highVol}</td><td>${money(r.turnover)}</td><td>${(r.leaders||[]).slice(0,4).map(i=>`${i.symbol} ${i.name}`).join('<br>')}</td></tr>`).join('')}</tbody></table>`);}
function scoreLine(i){const c=i.componentScores||{};return`<div class="score-breakdown">${[['T',c.trend],['M',c.momentum],['V',c.volume],['R',c.risk],['Theme',c.theme],['Setup',c.setup],['Liq',c.liquidity]].map(([k,v])=>`<span>${k}: <strong>${fmt(v)}</strong></span>`).join('')}</div>`;}
function metricsLine(i){const m=i.metrics||{};return`<div class="score-breakdown metrics-line">${[['20日',fmt(m.ret20Pct,'%')],['60日',fmt(m.ret60Pct,'%')],['ATR',fmt(m.atrPct,'%')],['高値比',fmt(m.drawdownFromHighPct,'%')],['売買代金',money(m.avgTradingValue20Usd)]].map(([k,v])=>`<span>${k}: <strong>${v}</strong></span>`).join('')}</div>`;}
function renderCandidates(){const all=currentReport.candidates||[];const list=filtered();setText('resultCount',`${list.length} / ${all.length}件を表示中`);if(!list.length){setHtml('candidateList','<p class="empty">条件に合う候補がありません。</p>');return;}setHtml('candidateList',list.map(i=>{const rs=(i.reasons||[]).slice(0,7).map(x=>`<li>${x}</li>`).join('');return`<article class="candidate-card"><div class="candidate-head"><div><span class="candidate-code">${i.symbol||i.code} / ${marketLabel(i.market)} / ${i.dataSource||'unknown'}</span><h3>${i.name}</h3><span class="theme-tag">#${i.theme||'未分類'} / ${i.setup||setupLabel(i.setupType)}</span></div><div class="rank-stack"><span class="rank-badge ${rankClass(i.rank)}">${i.rank||'-'}</span><small>${priority(i)}</small></div></div><div class="metric-grid"><div class="metric"><span class="metric-label">総合</span><strong>${fmt(i.score)}</strong></div><div class="metric"><span class="metric-label">型</span><strong>${setupLabel(i.setupType)}</strong></div><div class="metric"><span class="metric-label">現在値</span><strong>${fmt(i.price)}</strong></div><div class="metric"><span class="metric-label">損切り</span><strong>${fmt(i.stop)}</strong></div></div>${scoreLine(i)}${metricsLine(i)}<p class="action-line"><strong>判断:</strong> ${i.action||'監視継続'}</p><ul class="reason-list">${rs}</ul><div class="card-links">${links(i)}</div></article>`;}).join(''));}
function renderThemes(){const ts=currentReport.themes||[];setHtml('themeGrid',ts.map(t=>{const note=typeof t.note==='object'?Object.entries(t.note).map(([k,v])=>`${setupLabel(k)} ${v}`).join(' / '):(t.note||'');return`<article class="theme-card"><span>${(t.leaders||[]).join(' / ')||'leaders未設定'}</span><strong>${t.name}</strong><p>${note}</p><div class="theme-meter"><i style="width:${Math.max(0,Math.min(100,t.strength||0))}%"></i></div><span>Strength ${fmt(t.strength)}</span></article>`;}).join('')||'<p class="empty">テーマデータがありません。</p>');}
function renderRiskTable(){const rows=filtered();setHtml('riskTable',`<table><thead><tr><th>銘柄</th><th>市場</th><th>型</th><th>ランク</th><th>現在値</th><th>ピボット</th><th>損切り</th><th>利確1</th><th>売買代金</th><th>方針</th></tr></thead><tbody>${rows.map(i=>`<tr><td>${i.symbol||i.code}<br>${i.name}</td><td>${marketLabel(i.market)}</td><td>${setupLabel(i.setupType)}</td><td>${i.rank||'-'}</td><td>${fmt(i.price)}</td><td>${fmt(i.pivot)}</td><td>${fmt(i.stop)}</td><td>${fmt(i.target1)}</td><td>${money(i.metrics?.avgTradingValue20Usd)}</td><td>${i.action||'監視'}</td></tr>`).join('')}</tbody></table>`);}
function renderTracking(){const tr=currentReport.tracking||[];setHtml('trackingList',tr.map(i=>`<article class="tracking-card"><strong>${i.symbol} ${i.name}</strong><span>検出: ${i.detectedAt} / 経過: ${fmt(i.days,'日')}</span><p>最大上昇 ${fmt(i.maxGain,'%')} / 最大下落 ${fmt(i.maxDrawdown,'%')}</p><p class="tracking-status warn">${i.status}</p></article>`).join('')||'<p class="empty">検証データがありません。</p>');}
function renderAll(){setText('reportStatus',`Report: ${currentReport.generatedAt||'unknown'} / Universe: ${currentReport.universe||'unknown'} / JP・US別トップ${currentReport.screeningTopNPerMarket||'-'}`);renderSummary();renderMarketSummary();renderSectors();renderCandidates();renderThemes();renderRiskTable();renderTracking();}
async function loadReport(){setText('reportStatus','レポートを再読み込み中...');try{const res=await fetch(`reports/latest.json?ts=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error('not found');currentReport=await res.json();renderAll();}catch(e){setText('reportStatus','reports/latest.json の読み込みに失敗しました。Actionsを実行してください。');renderAll();}}
function bind(){['searchInput','marketFilter','rankFilter','setupFilter','sortSelect'].forEach(id=>{const e=$(id);if(!e)return;e.addEventListener('input',()=>{renderCandidates();renderRiskTable();});e.addEventListener('change',()=>{renderCandidates();renderRiskTable();});});$('sectorSortSelect')?.addEventListener('change',renderSectors);document.querySelectorAll('[data-sector-market]').forEach(btn=>btn.addEventListener('click',()=>{sectorMarket=btn.dataset.sectorMarket||'all';document.querySelectorAll('[data-sector-market]').forEach(b=>b.classList.toggle('active',b===btn));expandedSector='';renderSectors();}));document.addEventListener('click',e=>{const open=e.target.closest('[data-open-sector]');if(open){const key=open.dataset.openSector;expandedSector=expandedSector===key?'':key;renderSectors();return;}const filter=e.target.closest('[data-filter-theme]');if(filter){setCandidateTheme(filter.dataset.filterTheme,filter.dataset.filterMarket);}});$('reloadReport')?.addEventListener('click',loadReport);const ta=$('dailyNote');if(ta){const key='vcp-sepa-dashboard-note';ta.value=localStorage.getItem(key)||'';$('saveNote')?.addEventListener('click',()=>{localStorage.setItem(key,ta.value);alert('メモを保存しました');});$('clearNote')?.addEventListener('click',()=>{ta.value='';localStorage.removeItem(key);});}}
function init(){bind();loadReport();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
